vscode:
  extensions:
    - webfreak.code-d@0.22.0:K65wBqeoqTvGoea7XwBc+A==

    - grammarcraft.epsilon-eag@1.1.1:+leARWcfpaQ/ESbeXVSfXA==

    - grammarcraft.epsilon-eag-light-theme@1.1.1:1DNqc5cBo14/Wuf5wqKnEQ==

    - grammarcraft.epsilon-eag-dark-theme@1.1.1:nbJXLQVt1oKlkguAbGq+BQ==

image:
  file: .gitpod.Dockerfile

tasks:
  - init: dub test