vscode:
  extensions:
    - webfreak.code-d@0.22.0:K65wBqeoqTvGoea7XwBc+A==

    - grammarcraft.epsilon-eag@1.0.0:4ThXhBCaqSDqA0H3S5xo5w==

    - grammarcraft.epsilon-eag-light-theme@1.0.0:dOaZYnQHrqK4tM0WUx/GPw==

    - grammarcraft.epsilon-eag-dark-theme@1.0.0:j7hU12yAopJdvsyN+EHeCg==

image:
  file: .gitpod.Dockerfile

tasks:
  - init: dub test