vscode:
  extensions:
    - webfreak.code-d@0.22.0:K65wBqeoqTvGoea7XwBc+A==

    - grammarcraft.epsilon-eag-dark-theme@1.2.0:hIxn2b0W9rK4ECXYRwQvWQ==

    - grammarcraft.epsilon-eag-light-theme@1.2.0:lytiRWCRFOms8Q0rfUWD8g==

    - grammarcraft.epsilon-eag@1.2.0:BxvLqoM9/yCnyw2DYoMIFw==

image:
  file: .gitpod.Dockerfile

tasks:
  - init: dub test